[package]
name = "rusterlium"
version = "0.1.0"
authors = ["Sonny Scroggin <sonny@scrogg.in>"]
edition = "2018"

[dependencies]
rusterlium_codegen = { path = "../rusterlium_codegen" }
failure = "0.1.3"
failure_derive = "0.1.3"
